### ISSUE TITLE
MailComposer nema predvyplnene veci

### ISSUE THREAD

**Issue by vytick** [czechitas/iOS_app#15]
Kdyz je tam napistr nam, bylo by dobre alespon predvyplnit email, kam se to ma posilat

**Comment by vytick** [comment]
ted koukam, ze je to jen u nekterych

**Comment by vytick** [comment]
![img_0507](https://cloud.githubusercontent.com/assets/2011829/18416312/14da00f4-7811-11e6-8155-1be74d81441b.PNG)

**Comment by SvetlanaM** [comment]
asi nie je vyplnene na BE , este sa dohoduje na ktory email to bude posielane fixne, nieco ako napistenam@czechitas.cz alebo info, neviem este , donedavna tam boli emaily koucov, ale to sa zrusilo
