### ISSUE TITLE
tapnuti na obrazek hlavy vpravo nahore v detailu nedela nic

### ISSUE THREAD

**Issue by vytick** [czechitas/iOS_app#18]

**Comment by SvetlanaM** [comment]
no to je jedna vec co neviem ako aktualizovat hned, on ked sa nan klikne sa prida kurz do oblubenych ale neviem ako ho hned v tej chvili prekreslit, asi rovno po tom tapnuti ma teraz napadlo, alebo tam pridam alert ze kurz bol pridany do oblubenych a az potom ho prekreslim na plny
