### ISSUE TITLE
upravit barvy (a ikony a fonty a tak) ke kurzům podle Mirčiného manuálu https://drive.google.com/file/d/0B0U9ZIrCUrEcdWF3aWtpWjFvSlU/view

### ISSUE THREAD

**Issue by SvetlanaM** [czechitas/iOS_app#21]

**Comment by mijar** [comment]
Svetli hoď mi tu kdyžtak screen jak to teda teď vypadá...nebo rychlej link kde to najdu. díky.

**Comment by SvetlanaM** [comment]
![img_2252](https://cloud.githubusercontent.com/assets/3219358/21081135/c0726e3c-bfc0-11e6-9ea9-c06af6f6ccb5.PNG)

takto vyzerajú farby teraz, môžeš mi pre každú kategóriu poslať farbu?

**Comment by mijar** [comment]
Barvy:

datagirls jsou pod Data Academy #15BAE6  rgb(21, 186, 230)
jsem digitalni #008D36  rgb(0, 141, 54)
I am original #FFCB04 rgb(255, 203, 4)
I can code #8CC63E rgb(140, 198, 62)
Web development #F36F21 rgb(243, 111, 33)
Other (napr. Exceluju) #939597 rgb(147, 149, 151)

letniSkola #951B81 rgb(149, 27, 129)
meetupy #EC008B rgb(236, 0, 139)
akademieProgramovani #28225C  rgb(40, 34, 92)

**Comment by mijar** [comment]
A ty ikonky jsem ti posílala už dávno, i pro ten spodní panel...aktualizuješ to podle toho prosím?

**Comment by SvetlanaM** [comment]
ikonky sa tam nehodili a nepôsobilo to jednotne , upravím tú druhú zľava ako to bude a farby isto zmením

**Comment by mijar** [comment]
Ty ikonky ve spodním panelu teď ale nejsou vůbec čitelný, to že je všude noťas je zbytečný - šel, by úplně eliminovat protože do té ikony ti nedodává vůbec žádnou přidanou hodnotu...a pak jen ty hlavy v nich nedávaj smysl už vůbec...můžem to prosím odladit tak, aby to jednotně působilo a byly tam ty ikony, které dávaj smysl? u kurzů být teda nemusí když budou odděleny barvou a textovým popisem série, ale v tom spodním panelu by podle mě být měly. Jestli tam máš další ikony, které teď n tom screenu akortá nejsou vidět a potřebuješ to předělat taky do lineartu, ráda to udělám.

**Comment by mijar** [comment]
Jo a netuším co myslíš tím "upravím tu druhú zľava"

**Comment by SvetlanaM** [comment]
jaj no oki tak ja skusim tie od teba apošlem screen ako to vyzerá

**Comment by mijar** [comment]
díky
