### ISSUE TITLE
dám filtrovat, vyberu podle čeho, zobrazí se správný výsledek, ale když pak chci filtrování zrušit, tak v možnostech pro filtrování není nic zatržené (chybí tam fajfka)

### ISSUE THREAD

**Issue by SvetlanaM** [czechitas/iOS_app#26]

**Comment by SvetlanaM** [comment]
@ondra-marik neni som si istá, ako sa to robí defaultne? je všetko zašrktnuté? viem, že básnik to riešil v burde

**Comment by ondra-marik** [comment]
Ano a nakonec jsme to vyřešili tak, že když nezatrhneš nic tak je to stejně jako když zatrhneš vše - nemá smysl aby se nezobrazil žádný kurz. Sice nevím jestli jsou na takové chování zvyklí uživatelé ale pokud tam třeba nejsou kurzy bez kategorie, tak je to asi lepší.

**Comment by SvetlanaM** [comment]
no tiež to tak robím, kurzy bez kategorie hadam nie, neviem

**Comment by SvetlanaM** [comment]
hm..v burde to bolo ako? tá apka mi už nefunguje :D ale podľa mňa bude vyzerať divne, keď budú fajky všade, preto som to tam nedala

**Comment by ondra-marik** [comment]
V Burdě to bylo tak, že se filtr ukládal - tj. při znovuotevření tam bylo vybráno to co předtím :-)

**Comment by SvetlanaM** [comment]
jaj to tak nemalo byt :D ved som pvedala nech sa to tak nerobi
