### ISSUE TITLE
TableView

### ISSUE THREAD

**Issue by SvetlanaM** [czechitas/iOS_app#4]
Mam iba taku otazku, ako je lepsie robit tie nadpisy kurzov? ked vychadza jeden z 10 na 2 riadky? da sa to nejako automaticky zvetsovat alebo tam nechat iba ... ? lebo teraz som tam pre to dala vysku a pocet riadkov aby sa to zmestilo no nevyzera ta medzera dobre. alebo potom automaticky zmensovat pismo ale to sa mi nepaci.

**Comment by ondra-marik** [comment]
Samozřejmě dá, pokud ti stačí podpora iOS 8+. Když UILabel nastavíš (v IB nebo kódu) počet řádků (numberOfLines) na 0 a zalamování (lineBreakMode - word wrap nebo character wrap), tak se počet řádků labelu přizpůsobí obsahu.

V takovém případě s tím samozřejmě musí počítat i Cell - optimální v iOS8+ je nastavit tabulce výšku řádku (rowHeight) na UITableViewAutomaticDimension a estimatedRowHeight na přiměřenou hodnotu (příliš nezáleží jakou, prostě přibližně očekávanou). Potom se výška buňky automaticky počítá v runtime podle obsahu (https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/AutolayoutPG/WorkingwithSelf-SizingTableViewCells.html).

**Comment by SvetlanaM** [comment]
a netreba teda nijako nastavit vysku pre ten label? ved sa to tam nebude zmestit ak to bude na dva riadku potom nie?

**Comment by ondra-marik** [comment]
pokud UILabelu nenastavíš constrainty pro výšku, tak se počítá automaticky, stejně tak pro šířku. Jediné, co musíš pokud použiješ postup z předchozího komentáře je nastavit vzdálenosti mezi 
komponentami v buňce a buňkou, tak aby se výška buňky dala odvodit z obsahu.

Koukal jsem, že tam jsou 2-3 labely pod sebou, takže nastavit vzdálenost prvního od stropu buňky, pak mezi labely a posledního od spodu buňky. Asi bude ještě nutné nastavit některým vyšší content hugging prioritu, na to upozorní warning. To je ale formalita, na výsledný vzhled by to nemělo mít vliv.

**Comment by SvetlanaM** [comment]
aha, to staci iba to? tak to este dneska upravim lebo tie medzery tam vyzeraju takto divne

**Comment by ondra-marik** [comment]
Mělo by to stačit, kdyby byly problémy, tak jsem k dispozici.

**Comment by SvetlanaM** [comment]
tak uy to funguje len tie textz co su tam pre kazdy kurz su inak dlhe a takto to fakt nevyzera dobre, tak to orezem na prvych 125 znakov asi 

![simulator screen shot 16 6 2016 10 48 12](https://cloud.githubusercontent.com/assets/3219358/16110834/16178fea-33b0-11e6-86ac-d59847fd6f2e.png)

**Comment by SvetlanaM** [comment]
oki, upravila som v https://github.com/czechitas/iOS_app/commit/b4a937638490c901f301b58386ed9fd3d95f3244
