### ISSUE TITLE
upraviť ikonky v spodnom bare

### ISSUE THREAD

**Issue by SvetlanaM** [czechitas/iOS_app#43]

**Comment by SvetlanaM** [comment]
takto je to s novými ikonkami ![simulator screen shot 17 12 2016 12 56 34](https://cloud.githubusercontent.com/assets/3219358/21286576/4f4e2a7e-c458-11e6-8992-9cbafdbaca71.png)

**Comment by SvetlanaM** [comment]
potrebujem ešte ikonku pre bežiace kurzy - táto kategória pribudla nová

**Comment by SvetlanaM** [comment]
@einka - dáš vedieť Mirke? neviem ju tu tagnúť

**Comment by mijar** [comment]
co přesně znamenaj běžící kurzy? mám subscribe na všechny issues, checkuju to na mailu...

**Comment by mijar** [comment]
a nahoře je teda filtr a to druhý je pošta v jakým smyslu? nebo co to je :-) předělám to ve stejným stylu, nahoře jsou hranaté a dole kulaté, máme spíš všechny ikony ve stylu jak ty ve spodním baru

**Comment by SvetlanaM** [comment]
to druhe je email a bežiace kurzy sú tie, kde je uzavretá registrácia a konali sa za posledné tri mesiace alebo sa práve konajú ak sú dlhodobé
