### ISSUE TITLE
Načítanie dát

### ISSUE THREAD

**Issue by SvetlanaM** [czechitas/iOS_app#5]
Mám pár otázok. Dala som to dokopy drevorubačsky zatiaľ no chcela by som vedieť ako to asi funguje na pozadí . Mám dáta a načítavam ich v prepareForSegue kde ich rovno aj sťahujem. To predpokladám sa tak nerobí. Oni sa potom začnú naozaj vždy sťahovať keď sa prejde do detailu? Ak áno tak mi tam asi niečo chýba ako reloadData alebo tak, lebo najprv sú tie hodnoty prázdne a až keď prejdem druhý krát do detailu tabuľky sú tam už hodnoty správne.

![simulator screen shot 19 6 2016 14 16 56](https://cloud.githubusercontent.com/assets/3219358/16177446/c2221808-362d-11e6-9d40-58cf0322f0c7.png)
![simulator screen shot 19 6 2016 14 16 59](https://cloud.githubusercontent.com/assets/3219358/16177445/c2200612-362d-11e6-8e10-582684ab0d30.png)
![simulator screen shot 19 6 2016 14 17 04](https://cloud.githubusercontent.com/assets/3219358/16177443/c21fc38c-362d-11e6-9579-2235c2932b3b.png)
![simulator screen shot 19 6 2016 14 19 01](https://cloud.githubusercontent.com/assets/3219358/16177444/c21fde4e-362d-11e6-9608-2b3e0277cfa9.png)

**Comment by ondra-marik** [comment]
No tady máš v podstatě dvě možnosti, v podstatě ekvivalentní. Buď dáš načítání před _performSegue_ nebo pak až do funkce _viewDidLoad_ controlleru obrazovky detailu. V podstatě se to pak liší jen tím, jestli bude loading kolečko už v tabulce nebo v detailu.

Pokud stále používáš automatické segue z IB, tak načítání dat musíš mít ve _viewDidLoad_ controlleru detailu (případně možná _viewWill/DidAppear_, neměl by bý moc velký rozdíl.

Když je asynchronní načítání v _prepareForSegue_, tak upřímně si nejsem jistý, co se přesně stane, ale pravděpodobně se data načtou do proměnných v detailu příliš pozdě (na callback volající funkce nečeká).

**Comment by SvetlanaM** [comment]
ale potom je teda vždy lepšie ked tie data mam v jednom volani nie ? ked to aj tak volam v tom viewDidLoad alebo inde hned za sebou nie?

**Comment by ondra-marik** [comment]
Měla by jsi častěji pushovat, abych mohl lépe pochopit kontext, ale jasně, pokud chápu správně, tak je to lepší, pokud je všechna potřebuješ najednou.

**Comment by SvetlanaM** [comment]
jasne, zajtra alebo ak sa stretneme na obede ti to ukazem priamo. ja neviem potom ale skade budem mat to id toho kurzu na ktory sa kliklo aby som vedela ktory detail stiahnut, ale mozno sa to da asi ziskat z toho prepare for segue, neskusala som to este tak, tak to preberieme asi osobne.
<img width="1280" alt="snimek obrazovky 2016-06-19 v 21 23 01" src="https://cloud.githubusercontent.com/assets/3219358/16179692/ba9df242-366d-11e6-9011-867c9a341e52.png">

**Comment by ondra-marik** [comment]
Asi chápu, ale platí, co jsem řekl předtím, stahovat by se mělo buď před performSegue nebo až v cílovém VC. ID kurzu tam můžeš posílat stejně jako teď posíláš data kurzu :-) Jedna věc, co mě ještě trochu zaráží, že máš v tom cílovém proměnnou pro každý atribut kurzu. Nebylo by lepší tam posílat rovnou celý kurz a vytahování potřebných dat řešit až v něm?

**Comment by SvetlanaM** [comment]
neviem, tak som to videla v tych tutorialoch http://stackoverflow.com/questions/5210535/passing-data-between-view-controllers ale tiez sa mi to zda duplicitne

**Comment by ondra-marik** [comment]
Předávat objekt do dalšího VC po atributech je nesmysl, jestli to tam někdo psal, tak musel být hodně dole.... 

Buď tam předáš jen to course ID a podle něj budeš stahovat data v detailu nebo si data stáhneš předem a pak tam pošleš celý course. Takovéhle řešení na půl cesty nebude fungovat.

Hlavní problém je ale stále v tom, že stahuješ data v _prepareForSegue_, což se z dobrých důvodů nedělá.

**Comment by SvetlanaM** [comment]
uz som to prerobila , hned akos i mi potvrdil ze to moze byt aj inak :D ja som to to takto videla asi v piatich tutorialoch no teraz to mam iba takto vc.course = courseD
                vc.courseID = courseD.id a uz sa mi vyriesil aj problem so stahovanim dat

**Comment by ondra-marik** [comment]
Super, pokud tedy už funguje, tak se na zbytek podíváme až se potkáme nebo to pushneš na git.

**Comment by SvetlanaM** [comment]
no radšej osobne...mám pár otázok, funguje mi to ale nie je to až tak ako by som chcela apredstavovala by som si, tie data sa s alamofire stahuju vobec asynchronne? alebo sa zacnu naozaj stahovat az vo chvili ked sa pride na obrazovku s detailom? lebo to nechcem potom tak, sice to mam vo viewDidLoad chcela by som to prerobit to stahovanie

**Comment by ondra-marik** [comment]
Ano, data s Alamofire se obecně stahují asynchronně, ale jestli to máš správně nedokážu říci aniž bych viděl kód 😄  No nabízel jsem dvě základní možnosti, obě zahrnují načítání s využitím loading HUDu, takže ano, chvíli se musí někde čekat.

Jiné formy stahování jsou samozřejmě možné taky, v podstatě jde jen o to, kolik času a práce tomu chceš věnovat, protože to pak může být komplikovanější a je třeba řešit více věcí, jednotné řešení pro stahování dat jsem zatím nikde neobjevil.

**Comment by SvetlanaM** [comment]
no ten loading som tam chcela dostat ale dneska uz na to nemam asi silu :D no ja som to mala prvym sposobom ze sa to stahovalo v detaily ale to bolo vidno ze sa tie data postupne nacitavaju a teraz som to prerobila ze sa to stahuje uz v tom vypise a ked sa prejde do detailu su tam uz rovno bez cakania ale tu je ich tolko malo ze druhy sposob bude asi lepsi ale keby je to napriklad apka co ma tych dat naozaj vela asi sa to robi inak nie? nejako uz na pozadi sa zacnu stahovat este predtym ?

**Comment by ondra-marik** [comment]
Ano, v případě, že tam není tolik položek by to asi dávalo smysl stahovat rovnou všechno. Ale pokud nechceš stahovat a čekat na všechno najednou, tak by asi nejsnazší bylo stáhnout seznam (na který musíš počkat) a pak postupně stahovat detaily s tím, že stažení by využívalo NSNotification místo callbacku.

Potom ale musíš řešit, že při přechodu na detail nemusí být stažen (proto ta notifikace, aby detail veděl kdy byla data obnovena, v notifikaci se dají posílat data, aby detail poznal, že jsou ta jeho).

A kdyby to ještě nebylo dost komplikované, tak ohledně tohoto ses mě kdysi ptala na prioritu requestů, kdyby po příchodu na detail nebyla ještě data a ty chtěla urychleně stáhnout data pro ten konkrétní detail...
