### ISSUE TITLE
Konvertovanie instancie triedy zo stringu

### ISSUE THREAD

**Issue by SvetlanaM** [czechitas/iOS_app#6]
Je nejako mozne konvertovat stringove instancie triedy na realne instancie kurzu? Dala som uz dokopy to ukladanie do oblubenych ale nejako som zistila ze to nsuserdefaults nevie ulozit objekt tak som ho ulozila ako string no teraz to neviem previest spet na objekt. Da sa to ? Alebo z akeho formatu je mozne to previest na instanciu najlepsie?

**Comment by ondra-marik** [comment]
No hlavně není moudré ukládat objekty do NSUserDefaults. K tomu je minimálně NSCoding. Pokud se ale fakt chceš pokusit to ukládat do user defaults, tak jak jsi zjistila potřebuješ převést na standardní iOS datový typ a nejlepší by pro tohle byly asi NSData. A zde patrně stejně budeš muset implementovat NSCoding, viz jediná odpověď na http://stackoverflow.com/questions/19851510/convert-any-data-type-into-nsdata-and-back-again.

Druhou možností je neukládat objekt, ale už JSON v podobě NSDictionary (možná by fungoval i swiftí ekvivalent, nejsem si jistý).

**Comment by SvetlanaM** [comment]
no ja viem, ze to je na to, ale to ešte vôbec nepoznám ten NSCoding a všade som čítala že ak je to málo dát a podobne že stačí ten default a poradili mi to sa mi zdá aj na Faceboku no olutovala som to rýchlo, no zatial tie dáta budú iba online a potrebujem to iba na tie oblubene docasne, potom to isto prerobim. aha a tak ked implementujem nscoding to nsuserdefaults nemusim, ono to tam je ako dictionary no na prechod do detailu v tabulke tam posielam instanciu kurzu a tu ziadnu nemam cize sa do detailu nedostanem

**Comment by ondra-marik** [comment]
Ano, ale málem dat se myslí spíš věci jako login, drobné nastavení, vybrané téma a tak. Ukládat jakákoliv data, kterých může být 1...n není good practice ani dobrý nápad.

Vtipné je, že implementace tohohle by ti zabrala prakticky stejně jako kdybys to ukládala normálně do dokumentů s NSCoding.

**Comment by SvetlanaM** [comment]
ved mi to aj zabralo tak ja sa naucim ten NSCoding ale nasla som asi tisic nedokoncenych tutorialov na to, asi obrazovku moje kurzy prerobim a toto spravim uz cez jul

**Comment by ondra-marik** [comment]
NSCoding je triviální, stačí jen implementovat pro každý objekt NSCoding, což jsou dvě funkce a pak můžeš klidně ukládat celé pole takových objektů jednou funkcí (http://nshipster.com/nscoding/).

**Comment by SvetlanaM** [comment]
to je vsetko? iba to co je v tom tutorialy? ale ked to takto ulozim ak to chapem spravne tie data budu dostupne uz aj bez netu vsak? ak ich budem brat z toho suboru ulozeneho na systeme

**Comment by ondra-marik** [comment]
Ano, pokud si je někdy předtím stáhneš a uložíš, tak tam budou a můžeš je načítat.
