### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by SvetlanaM** [czechitas/iOS_app#8]
Ak by si mal niekedy cas spravil by si ten filter? Ja asi viem ako by som to robila teoreticky, ze by som si v modalnom okne alebo popupe zobrazila tabulku, nastavila cell, dala tam z api kategorie a potom asi ulozila vybrane hodnoty (to sa robi akototo?) od uzivatela a podla nich filtrovala to pole kurzov.

Link na popis -- https://github.com/czechitas/iOS_app/wiki/Filtrova%C5%A5

**Comment by ondra-marik** [comment]
Ano, dnes nebo zítra to můžu udělat. Postup máš zhruba správně, jestli jsou ty kategorie z api, tak bys to mohla ukládat podobně jako ukládáš oblíbené kurzy. A pole kurzů se pak obvykle filtruje do druhého pole, ze kterého si to bere tableview.

**Comment by SvetlanaM** [comment]
NO to neponáhľa, kludne stačí niekedy v priebehu júla

**Comment by SvetlanaM** [comment]
Zatiaľ si tento task dávam na seba, a skúsim to aspoň podľa kategórie sama urobiť.

**Comment by ondra-marik** [comment]
Ok, bral jsem, že když to bylo odloženo, tak si to zkusíš sama. Klidně s tím poradím více.

**Comment by SvetlanaM** [comment]
uz iba odladim
